CREATE DATABASE IF NOT EXISTS employee_db; USE employee_db;
CREATE TABLE IF NOT EXISTS employees (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) NOT NULL, email VARCHAR(120) UNIQUE NOT NULL, department VARCHAR(80) NOT NULL, salary DECIMAL(10,2) NOT NULL);
